name: libcrypto
description: Cryptography utility library for AES encryption and Pbkdf2 hashing algorithms.
version: 0.2.1
repository: https://github.com/BytePass/libcrypto-dart

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  pointycastle: ^3.6.2
  hex: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
