name: libcrypto
description: Cryptography utility library
version: 0.1.0
repository: https://github.com/BytePass/libcrypto-dart
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cryptography: ^2.0.5
  hex: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
